name: test
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/test.yml
      - bin/ci
      - Sources
      - Tests
      - Package.resolved
      - Package.swift

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    env:
      SWIFT: swift-DEVELOPMENT-SNAPSHOT-2024-04-27-a
      SWIFT_WASM: swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-28-a
    steps:
      - uses: actions/checkout@v4
      - run: bin/ci/check-package.sh

      - run: >
          sudo apt-get update &&
          sudo apt-get install -y
          binutils
          git
          gnupg2
          libc6-dev
          libcurl4-openssl-dev
          libedit2
          libgcc-9-dev
          libpython3.8
          libsqlite3-0
          libstdc++-9-dev
          libxml2-dev
          libz3-dev
          pkg-config
          tzdata
          unzip
          zlib1g-dev
          curl
          binaryen

      - run: curl -fLO https://download.swift.org/development/ubuntu2204/${{ env.SWIFT }}/${{ env.SWIFT }}-ubuntu22.04.tar.gz
        working-directory: /home/runner
      - run: sudo tar -xf ${{ env.SWIFT }}-ubuntu22.04.tar.gz --strip-components=2 -C /usr/local
        working-directory: /home/runner
      - run: swift --version

      - run: >
          swift sdk install
          https://github.com/swiftwasm/swift/releases/download/${{ env.SWIFT_WASM }}/${{ env.SWIFT_WASM }}-wasm32-unknown-wasi.artifactbundle.zip
      - run: swift sdk list

      - run: curl -fLO https://github.com/omochi/carton-build/releases/download/snapshot-2024-04-16/carton.tar.gz
        working-directory: /home/runner
      - run: sudo tar -xf carton.tar.gz --strip-components=1 -C /usr/local/bin
        working-directory: /home/runner
      - run: carton --version

      - run: swift package resolve
      - run: swift build --build-tests
      - run: swift test

      - run: >
          swift build --swift-sdk wasm32-unknown-wasi
          --build-tests
          --static-swift-stdlib
          -Xswiftc -Xclang-linker -Xswiftc -mexec-model=reactor
          -Xlinker --export-if-defined=__main_argc_argv
          --disable-build-manifest-caching
          -Xlinker --stack-first
          -Xlinker --global-base=1048576
          -Xlinker -z -Xlinker stack-size=1048576
      - run: >
          CartonFrontend test
          --prebuilt-test-bundle-path .build/debug/swift-reactPackageTests.wasm
          --environment browser --headless
        env:
          WEBDRIVER_PATH: /usr/bin/chromedriver
     
      - run: ./BrowserTests/bin/build
      

